# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionInstance',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(help_text='Enter a question that thrills you about a potential roomate!', max_length=200)),
                ('vetted', models.BooleanField(default=False)),
                ('question_answers', models.CharField(blank=True, choices=[('1', 'Not Important At all'), ('25', 'Somewhat Important'), ('150', 'Very Important'), ('250', 'Mandatory')], help_text='Answer Weighting', max_length=3)),
            ],
            options={
                'ordering': ['?'],
            },
        ),
    ]
