# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioninstance',
            name='question_answers',
            field=models.CharField(blank=True, choices=[('1', 'Not Important At all'), ('25', 'Somewhat Important'), ('150', 'Very Important'), ('250', 'Mandatory')], default='1', help_text='Answer Weighting', max_length=3),
        ),
    ]
