# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0003_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer',
            field=models.IntegerField(default=1),
        ),
    ]
