# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0005_auto_20170504_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioninstance',
            name='question_option_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='questioninstance',
            name='question_option_2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='questioninstance',
            name='question_option_3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='questioninstance',
            name='question_option_4',
            field=models.CharField(default='', max_length=200),
        ),
    ]
