# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0006_auto_20170504_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer',
            field=models.IntegerField(default=1),
        ),
    ]
