# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0008_auto_20170504_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioninstance',
            name='question_weights',
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer_weight',
            field=models.CharField(blank=True, choices=[('1', 'Not Important At all'), ('25', 'Somewhat Important'), ('150', 'Very Important'), ('250', 'Mandatory')], default='1', help_text='Answer Weighting', max_length=3),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matcher.QuestionInstance', unique=True),
        ),
    ]
