# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0010_auto_20170505_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matcher.QuestionInstance'),
        ),
    ]
