# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0015_auto_20170505_0607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='user',
            new_name='answer_user',
        ),
    ]
