# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0018_auto_20170505_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
