# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 06:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matcher', '0021_answers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='user',
        ),
        migrations.AddField(
            model_name='answers',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
