# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0022_auto_20170505_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
