# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0023_auto_20170505_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='user_id',
            new_name='created_by',
        ),
    ]
