# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0026_auto_20170505_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='has_answered',
            field=models.BooleanField(default=False),
        ),
    ]
