# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0027_answers_has_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('question_id', models.IntegerField(default=0)),
                ('answer_weight', models.IntegerField(default=0)),
                ('question_answer', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='questioninstance',
            options={},
        ),
        migrations.RemoveField(
            model_name='questioninstance',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='questioninstance',
            name='question_option_3',
        ),
        migrations.RemoveField(
            model_name='questioninstance',
            name='question_option_4',
        ),
        migrations.AddField(
            model_name='questioninstance',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='answers',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='has_answered',
        ),
    ]
