# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0028_auto_20170506_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
