# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0029_answers_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='question',
        ),
        migrations.AddField(
            model_name='answers',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questioninstance',
            name='question_ideal',
            field=models.CharField(default='No', max_length=200),
        ),
    ]
