# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0032_auto_20170507_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer_ideal',
            field=models.IntegerField(default=1),
        ),
    ]
