# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0035_questioninstance_submitted_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioninstance',
            name='question_weight',
            field=models.IntegerField(default=1, max_length=3),
        ),
    ]
