# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0036_auto_20170507_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='user_id',
            new_name='user',
        ),
    ]
