# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0037_auto_20170507_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioninstance',
            name='question_ideal',
        ),
        migrations.RemoveField(
            model_name='questioninstance',
            name='question_weight',
        ),
    ]
