# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0042_auto_20170507_2311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAnswers',
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer_weight',
            field=models.CharField(choices=[('Not Important At all', '1'), ('Somewhat Important', '75'), ('Very Important', '125'), ('Mandatory', '250')], default='1', help_text='Answer Weighting', max_length=3),
        ),
    ]
