# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0049_auto_20170509_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='importance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
