# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0050_auto_20170509_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='importance',
            new_name='importance_one',
        ),
        migrations.AddField(
            model_name='matches',
            name='importance_two',
            field=models.IntegerField(default=0),
        ),
    ]
