# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0052_matches_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='match_percent',
            field=models.FloatField(default=0),
        ),
    ]
