# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0057_auto_20170510_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer_weight',
            field=models.CharField(choices=[('0', 'Irrelevant'), ('1', 'Somewhat Important'), ('10', 'Very Important'), ('250', 'Mandatory')], default='1', help_text='How important is this question to you?', max_length=3),
        ),
    ]
